<a href="https://colab.research.google.com/github/mariahelenass/QuantumComputing/blob/main/qiskit_and_complex_numbers(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import qiskit

In [ ]:
qiskit.__version__

'1.0.2'

In [ ]:
import numpy as np

In [ ]:
# define a complex number
a = 5 + 3j
print(a)

(5+3j)


In [ ]:
# module
print(abs(a))

5.830951894845301


In [ ]:
# division
print((5 + 3j)/(3 + 1j))

(1.7999999999999998+0.4j)


In [ ]:
# real
a.real

5.0

In [ ]:
# imaginary
a.imag

3.0

In [ ]:
# conjugate
np.conjugate(a)

(5-3j)

In [ ]:
# line vector
v0l = np.array([[1,0]])
print(v0l)

[[1 0]]


In [ ]:
# col vector
v0c = np.array([ [1],[0] ])
print(v0c)

[[1]
 [0]]


In [ ]:
# product
v0l@v0c

array([[1]])

In [ ]:
v0c@v0l

array([[1, 0],
       [0, 0]])

In [ ]:
v1c = np.array([ [0],[1] ])

In [ ]:
print(v0c)
print(v1c)

[[1]
 [0]]
[[0]
 [1]]


In [ ]:
psi = (3 + 1j) * v0c + (5 - 2j) * v1c
print(psi)

[[3.+1.j]
 [5.-2.j]]


In [ ]:
print(np.conj(psi))

[[3.-1.j]
 [5.+2.j]]


In [ ]:
# transpose
psid = np.transpose(np.conj(psi))
print(psid)

[[3.-1.j 5.+2.j]]


In [ ]:
psid@psi

array([[39.+0.j]])

In [ ]:
# quantum state
normalize = (3 + 1j)*v0c/np.sqrt(39) + (5 - 2j)*v1c/np.sqrt(39)
print(normalize)

[[0.48038446+0.16012815j]
 [0.80064077-0.32025631j]]


In [ ]:
psid_normalized = np.transpose(np.conj(normalize))

In [ ]:
psid_normalized@normalize

array([[1.+0.j]])

In [ ]:
sz = np.array([ [1, 0],[0, -1] ])

In [ ]:
psi

array([[0.48038446+0.16012815j],
       [0.80064077-0.32025631j]])

In [ ]:
sz@psi

array([[ 0.48038446+0.16012815j],
       [-0.80064077+0.32025631j]])

In [ ]:
sx = np.array([ [0, 1],[1, -0] ])
print(sx)

[[0 1]
 [1 0]]


In [ ]:
sx@psi

array([[0.80064077-0.32025631j],
       [0.48038446+0.16012815j]])